### ISSUE TITLE
Override encription keys in production

### ISSUE THREAD

**Issue by lightway82** [eignatik/petpool#32]
It is necessary to redefine two keys from the config in production. This can be done by file that will be read by code or from a startup script, through Java arguments

encryption.key=Y2F0T........MTIzIQ==
encryption.key.jwt=DnFf2.........joe9qWLcD1s=

**Comment by eignatik** [comment]
The wiki page is created https://github.com/eignatik/petpool/wiki/Configure-encryption-keys-for-application
