### ISSUE TITLE
Project on-boarding

### ISSUE THREAD

**Issue by eignatik** [eignatik/petpool#34]
## Description
Это вводная задача на проекте, на которую дается неделя. В рамках этой задачи необходимо ознакомиться с проектом, развернуть его на своей локальной машине, убедиться, что все запускается и работает. Так же необходимо пройти две knowledge transfer сессии, которые будут в среду и в воскресенье (во время митингов).
Так же в этой задачи удастся познакомиться с процессами в организации работы на проекте - работа с доской, задачами, лейблами, и так далее.

## DoD
1. Каждый assignee отписался в комментариях, что он успешно развернул проект локально: проект back-end выкачан, собран, запущен без ошибок; front-end проект выкачан, собран, запущен; на странице dashboard на клиенте вы видите сообщение `Server status: up&running`
1. Каждый assignee прослушал два тех толка с передачей знаний по проекту
1. Каждый assignee получил свою первую задачу на следующий спринт

## Implementation note
1. Чтобы разобраться с развертыванием проекта локально, обратитесь к документации в Wiki.

**Comment by Darthyk** [comment]
Поднял

**Comment by vadjradanta** [comment]
проект запустил, Спасибо Николаю за руководство
